{ region:
   { span:
      { latitude_delta: 0.034065532334906834,
        longitude_delta: 0.04184730419760285 },
     center: { latitude: 45.5084562671205, longitude: -73.574221598092 } },
  total: 8824,
  businesses:
   [ { is_claimed: true,
       rating: 4.5,
       mobile_url: 'http://m.yelp.ca/biz/restaurant-ruby-burma-montr%C3%A9al',
       rating_img_url: 'http://s3-media2.ak.yelpcdn.com/assets/2/www/img/99493c12711e/ico/stars/v1/stars_4_half.png',
       review_count: 21,
       name: 'Restaurant Ruby Burma',
       snippet_image_url: 'http://s3-media3.ak.yelpcdn.com/photo/1U07PX0aKRib46xBfNL1nQ/ms.jpg',
       rating_img_url_small: 'http://s3-media2.ak.yelpcdn.com/assets/2/www/img/a5221e66bc70/ico/stars/v1/stars_small_4_half.png',
       url: 'http://www.yelp.ca/biz/restaurant-ruby-burma-montr%C3%A9al',
       phone: '5149859559',
       snippet_text: 'My last meal of 2013 summed up an amazing year: trying new things and great food.\n\nNever tried Burmese cuisine before, but if this is what it tastes like...',
       image_url: 'http://s3-media1.ak.yelpcdn.com/bphoto/sbmy-KyDWLjFlApLND8Xsw/ms.jpg',
       categories: [Object],
       display_phone: '+1-514-985-9559',
       rating_img_url_large: 'http://s3-media4.ak.yelpcdn.com/assets/2/www/img/9f83790ff7f6/ico/stars/v1/stars_large_4_half.png',
       id: 'restaurant-ruby-burma-montréal',
       is_closed: false,
       location: [Object] },
     { is_claimed: true,
       rating: 4.5,
       mobile_url: 'http://m.yelp.ca/biz/tourti%C3%A8re-australienne-montr%C3%A9al-2',
       rating_img_url: 'http://s3-media2.ak.yelpcdn.com/assets/2/www/img/99493c12711e/ico/stars/v1/stars_4_half.png',
       review_count: 39,
       name: 'Tourtière Australienne',
       snippet_image_url: 'http://s3-media2.ak.yelpcdn.com/photo/JYmGUDrgptGUUJQfexSZcQ/ms.jpg',
       rating_img_url_small: 'http://s3-media2.ak.yelpcdn.com/assets/2/www/img/a5221e66bc70/ico/stars/v1/stars_small_4_half.png',
       url: 'http://www.yelp.ca/biz/tourti%C3%A8re-australienne-montr%C3%A9al-2',
       phone: '5142777437',
       snippet_text: 'Meat pies were one of the highlights of our trip to Australia/New Zealand. The only disappointment we had in discovering this place is that we didn\'t find...',
       image_url: 'http://s3-media3.ak.yelpcdn.com/bphoto/grvRUVuNe4-kO1hvBftORg/ms.jpg',
       categories: [Object],
       display_phone: '+1-514-277-7437',
       rating_img_url_large: 'http://s3-media4.ak.yelpcdn.com/assets/2/www/img/9f83790ff7f6/ico/stars/v1/stars_large_4_half.png',
       id: 'tourtière-australienne-montréal-2',
       is_closed: false,
       location: [Object] }
    ]
}
