{ is_claimed: true,
  rating: 2.5,
  mobile_url: 'http://m.yelp.com/biz/yelp-san-francisco',
  rating_img_url: 'http://s3-media4.ak.yelpcdn.com/assets/2/www/img/c7fb9aff59f9/ico/stars/v1/stars_2_half.png',
  review_count: 5671,
  name: 'Yelp',
  snippet_image_url: 'http://s3-media1.ak.yelpcdn.com/photo/bGunGlOyo_FFrYA1vtihZQ/ms.jpg',
  rating_img_url_small: 'http://s3-media4.ak.yelpcdn.com/assets/2/www/img/8e8633e5f8f0/ico/stars/v1/stars_small_2_half.png',
  url: 'http://www.yelp.com/biz/yelp-san-francisco',
  reviews:
   [ { rating: 1,
       excerpt: 'would give zero stars for this company but you cant. here what was sent to me from a no reply email..\n\nHi Gabriel,\n\nWe wanted to let you know that we\'ve...',
       time_created: 1392869135,
       rating_image_url: 'http://s3-media1.ak.yelpcdn.com/assets/2/www/img/f64056afac01/ico/stars/v1/stars_1.png',
       rating_image_small_url: 'http://s3-media1.ak.yelpcdn.com/assets/2/www/img/74cb12ae7253/ico/stars/v1/stars_small_1.png',
       user: [Object],
       rating_image_large_url: 'http://s3-media3.ak.yelpcdn.com/assets/2/www/img/cc5d90a21966/ico/stars/v1/stars_large_1.png',
       id: 'vGHsdHIWCkxvBCsYr-KUPQ' } ],
  phone: '4159083801',
  snippet_text: 'Love yelp! and post regularly... Moving to the Bay Area in March and would love to work with you!!!!\n\nPlease see my resume below...\n\n\nJuan Carlos...',
  image_url: 'http://s3-media3.ak.yelpcdn.com/bphoto/4LSTYqXkQ-YrI1CQmr2dQA/ms.jpg',
  categories:
   [ [ 'Local Flavor', 'localflavor' ],
     [ 'Mass Media', 'massmedia' ] ],
  display_phone: '+1-415-908-3801',
  rating_img_url_large: 'http://s3-media2.ak.yelpcdn.com/assets/2/www/img/d63e3add9901/ico/stars/v1/stars_large_2_half.png',
  id: 'yelp-san-francisco',
  is_closed: false,
  location:
   { cross_streets: 'Natoma St & Minna St',
     city: 'San Francisco',
     display_address:
      [ '140 New Montgomery St',
        '(b/t Natoma St & Minna St)',
        'Financial District',
        'San Francisco, CA 94105' ],
     neighborhoods: [ 'Financial District', 'SoMa' ],
     postal_code: '94105',
     country_code: 'US',
     address: [ '140 New Montgomery St' ],
     state_code: 'CA' } }
